<?php

use Illuminate\Database\Seeder;

class LearningStylesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('learning_styles')->insert([
            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '12', 
            'ca_ec' => '0', 
            'ea_or' =>  '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '17', 
            'ea' => '18', 
            '_or' => '19', 
            'ca_ec' => '-1',	 
            'ea_or' => '-1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '13', 
            'ea' => '17', 
            '_or' => '17', 
            'ca_ec' => '2', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '11', 'ec' => '19', 
            'ea' => '16', 
            '_or' => '16', 
            'ca_ec' => '-8', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '14', 
            'ea' => '19', 
            '_or' => '18', 
            'ca_ec' => '5', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '17', 
            'ea' => '16', 
            '_or' => '15', 
            'ca_ec' => '-1', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '11', 
            'ea' => '19', 
            '_or' => '17', 
            'ca_ec' => '8', 
            'ea_or' => '2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '14', 
            'ea' => '21', 
            '_or' => '13', 
            'ca_ec' => '-1', 
            'ea_or' => '8',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '21', 'ec' => '14', 
            'ea' => '12', 
            '_or' => '18', 
            'ca_ec' => '7',	 
            'ea_or' => '-6',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '19', 
            'ca_ec' => '1',	 
            'ea_or' => '-1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '10', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '8', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '17', 
            'ea' => '19', 
            '_or' => '15', 
            'ca_ec' => '-2', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '21', 'ec' => '10', 
            'ea' => '11', 
            '_or' => '23', 
            'ca_ec' => '11', 
            'ea_or' => '-12',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '13', 
            'ea' => '16', 
            '_or' => '15', 
            'ca_ec' => '4', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '16', 
            'ea' => '13', 
            '_or' => '17', 
            'ca_ec' => '-1',	 
            'ea_or' => '-4',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '11', 
            'ea' => '20', 
            '_or' => '12', 
            'ca_ec' => '5', 
            'ea_or' => '8',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '11', 
            'ea' => '21', 
            '_or' => '18', 
            'ca_ec' => '7', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '15', 
            'ca_ec' => '1', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '18', 
            'ea' => '20', 
            '_or' => '11', 
            'ca_ec' => '1', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '11', 
            'ea' => '17', 
            '_or' => '14', 
            'ca_ec' => '7', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '10', 'ec' => '17', 
            'ea' => '17', 
            '_or' => '17', 
            'ca_ec' => '-7', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '14', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '13', 
            'ea' => '20', 
            '_or' => '13', 
            'ca_ec' => '4', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '10', 'ec' => '15', 
            'ea' => '16', 
            '_or' => '19', 
            'ca_ec' => '-5',	 
            'ea_or' => '-3',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '20', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '12', 
            'ca_ec' => '8', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '17', 
            'ea' => '15', 
            '_or' => '18', 
            'ca_ec' => '2',	 
            'ea_or' => '-3',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '12', 
            'ea' => '14', 
            '_or' => '23', 
            'ca_ec' => '3',	 
            'ea_or' => '-9',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '16', 
            'ea' => '12', 
            '_or' => '20', 
            'ca_ec' => '-1',	 
            'ea_or' => '-8',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '14', 
            'ea' => '13', 
            '_or' => '17', 
            'ca_ec' => '4',	 
            'ea_or' => '-4',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '8', 
            'ea' => '12', 
            '_or' => '21', 
            'ca_ec' => '11',	 
            'ea_or' => '-9',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '20', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '15', 
            'ca_ec' => '5', 
            'ea_or' => '0',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '7', 'ec' => '19', 
            'ea' => '19', 
            '_or' => '15', 
            'ca_ec' => '-12', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '21', 'ec' => '10', 
            'ea' => '20', 
            '_or' => '10', 
            'ca_ec' => '11',	 
            'ea_or' => '10',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '9', 
            'ea' => '24', 
            '_or' => '14', 
            'ca_ec' => '5',	 
            'ea_or' => '10',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '11', 
            'ea' => '18', 
            '_or' => '18', 
            'ca_ec' => '6', 
            'ea_or' => '0',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '12', 
            'ea' => '17', 
            '_or' => '16', 
            'ca_ec' => '6', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '11', 
            'ea' => '14', 
            '_or' => '19', 
            'ca_ec' => '5',	 
            'ea_or' => '-5',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '5', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '20', 'ec' => '14', 
            'ea' => '19', 
            '_or' => '10', 
            'ca_ec' => '6', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '16', 
            'ea' => '20', 
            '_or' => '10', 
            'ca_ec' => '0',	 
            'ea_or' => '10',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '14', 
            'ca_ec' => '0', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '20', 'ec' => '13', 
            'ea' => '14', 
            '_or' => '12', 
            'ca_ec' => '7', 
            'ea_or' => '2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '22', 'ec' => '10', 
            'ea' => '18', 
            '_or' => '12', 
            'ca_ec' => '12', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '15', 
            'ea' => '17', 
            '_or' => '18', 
            'ca_ec' => '0',	 
            'ea_or' => '-1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '17', 
            'ea' => '13', 
            '_or' => '23', 
            'ca_ec' => '-1', 
            'ea_or' => '-10',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '12', 
            'ea' => '17', 
            '_or' => '18', 
            'ca_ec' => '3',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '11', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '5', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '11', 'ec' => '16', 
            'ea' => '20', 
            '_or' => '14', 
            'ca_ec' => '-5', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '14', 
            'ca_ec' => '5', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '16', 
            'ea' => '17', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '15', 
            'ea' => '20', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '16', 
            'ca_ec' => '0', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '11', 
            'ea' => '15', 
            '_or' => '20', 
            'ca_ec' => '8',	 
            'ea_or' => '-5',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '17', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '8',	 
            'ca_ec' => '3',	 
            'ea_or' => '12',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '24', 'ec' => '12', 
            'ea' => '12', 
            '_or' => '14', 
            'ca_ec' => '12',	 
            'ea_or' => '-2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '18', 'ec' => '14', 
            'ea' => '13', 
            '_or' => '18', 
            'ca_ec' => '4',	 
            'ea_or' => '-5',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '21', 'ec' => '11', 
            'ea' => '18', 
            '_or' => '13', 
            'ca_ec' => '10', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '12', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '19', 
            'ca_ec' => '-2',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '17', 
            'ca_ec' => '1', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '16', 
            'ea' => '16', 
            '_or' => '16', 
            'ca_ec' => '-2', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '14', 
            'ea' => '19', 
            '_or' => '10', 
            'ca_ec' => '5', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '15', 
            'ea' => '14', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '0',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '15', 'ec' => '18', 
            'ea' => '18', 
            '_or' => '13', 
            'ca_ec' => '-3', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '12', 'ec' => '17', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '-5', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '16', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '0', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '19', 
            'ca_ec' => '-2', 
            'ea_or' => '2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '19', 'ec' => '14', 
            'ea' => '19', 
            '_or' => '10', 
            'ca_ec' => '5', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '16', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '0', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Paraiso',
            'ca' => '13', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '17', 
            'ca_ec' => '1', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '14', 'ec' => '11', 
            'ea' => '19', 
            '_or' => '18', 
            'ca_ec' => '3', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Paraiso',
            'ca' => '16', 'ec' => '10', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '6', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Paraiso',
            'ca' => '9', 'ec' => '16', 
            'ea' => '24', 
            '_or' => '13', 
            'ca_ec' => '-7',	 
            'ea_or' => '11',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '13', 
            'ea' => '13', 
            '_or' => '20', 
            'ca_ec' => '6',	 
            'ea_or' => '-7',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '11', 
            'ea' => '14', 
            '_or' => '17', 
            'ca_ec' => '8',	 
            'ea_or' => '-3',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '12', 
            'ea' => '21', 
            '_or' => '14', 
            'ca_ec' => '6', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '16', 
            'ea' => '13', 
            '_or' => '16', 
            'ca_ec' => '3',	 
            'ea_or' => '-3',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '13', 
            '_or' => '18', 
            'ca_ec' => '2',	 
            'ea_or' => '-5',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '12', 
            'ca_ec' => '5', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '17', 
            'ca_ec' => '2',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '17', 
            'ea' => '12', 
            '_or' => '21', 
            'ca_ec' => '-5',	 
            'ea_or' => '-9',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '15', 
            'ea' => '20', 
            '_or' => '16', 
            'ca_ec' => '-4', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '15', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '-2', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '17', 
            'ca_ec' => '-1',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '11', 
            'ea' => '18', 
            '_or' => '15', 
            'ca_ec' => '3', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '17', 
            'ea' => '14', 
            '_or' => '21', 
            'ca_ec' => '-1',	 
            'ea_or' => '-7',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '13', 
            'ea' => '22', 
            '_or' => '11', 
            'ca_ec' => '4',	 
            'ea_or' => '11',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '15', 
            'ea' => '16', 
            '_or' => '18', 
            'ca_ec' => '-3',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '9', 'ec' => '21', 
            'ea' => '18', 
            '_or' => '17', 
            'ca_ec' => '-12', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '15', 
            'ca_ec' => '7', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '14', 
            'ea' => '16', 
            '_or' => '18', 
            'ca_ec' => '3',	 
            'ea_or' => '-2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '13', 
            'ea' => '11', 
            '_or' => '19', 
            'ca_ec' => '7',	 
            'ea_or' => '-8',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '12', 
            'ea' => '14', 
            '_or' => '19', 
            'ca_ec' => '4',	 
            'ea_or' => '-5',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '13', 
            'ea' => '16', 
            '_or' => '15', 
            'ca_ec' => '4', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '16', 
            'ea' => '17', 
            '_or' => '19', 
            'ca_ec' => '-5',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '12', 
            'ea' => '21', 
            '_or' => '15', 
            'ca_ec' => '5', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '14', 
            'ea' => '21', 
            '_or' => '9', 
            'ca_ec' => '5',	 
            'ea_or' => '12',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '15', 
            'ca_ec' => '1', 
            'ea_or' => '2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '10', 
            'ea' => '18', 
            '_or' => '12', 
            'ca_ec' => '10', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '18', 
            'ea' => '13', 
            '_or' => '14', 
            'ca_ec' => '-4',	 
            'ea_or' => '-1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '18', 
            'ca_ec' => '4',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '14', 
            'ea' => '12', 
            '_or' => '18', 
            'ca_ec' => '3',	 
            'ea_or' => '-6',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '11', 
            'ea' => '21', 
            '_or' => '12', 
            'ca_ec' => '8', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '14', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '3', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '-3', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '13', 
            'ea' => '17', 
            '_or' => '16', 
            'ca_ec' => '4', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '13', 
            'ca_ec' => '0', 
            'ea_or' => '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '20', 
            '_or' => '13', 
            'ca_ec' => '-2', 
            'ea_or' => '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '13', 
            'ea' => '20', 
            '_or' => '16', 
            'ca_ec' => '4', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '14', 
            'ea' => '16', 
            '_or' => '15', 
            'ca_ec' => '-1', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '19', 
            '_or' => '15', 
            'ca_ec' => '-2', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '-4', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '3', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '15', 
            'ea' => '16', 
            '_or' => '21', 
            'ca_ec' => '-4',	 
            'ea_or' => '-5',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '12', 
            'ea' => '19', 
            '_or' => '16', 
            'ca_ec' => '5', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '17', 
            'ea' => '19', 
            '_or' => '15', 
            'ca_ec' => '-3', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '9', 
            'ea' => '23', 
            '_or' => '10', 
            'ca_ec' => '10',	 
            'ea_or' => '13',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '17', 
            '_or' => '18', 
            'ca_ec' => '-2',	 
            'ea_or' => '-1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '12', 
            'ea' => '15', 
            '_or' => '16', 
            'ca_ec' => '4',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '15', 
            'ea' => '16', 
            '_or' => '13', 
            'ca_ec' => '3', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '17', 
            'ea' => '14', 
            '_or' => '18', 
            'ca_ec' => '-3',	 
            'ea_or' => '-4',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '13', 
            'ea' => '22', 
            '_or' => '12', 
            'ca_ec' => '3',	 
            'ea_or' => '10',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '16', 
            'ca_ec' => '-2', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '17', 
            'ca_ec' => '0', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '8', 
            'ea' => '18', 
            '_or' => '18', 
            'ca_ec' => '9', 
            'ea_or' => '0',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '10', 
            'ea' => '15', 
            '_or' => '20', 
            'ca_ec' => '8',	 
            'ea_or' => '-5',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '9', 
            'ca_ec' => '3',	 
            'ea_or' => '10',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '15', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '18', 
            '_or' => '15', 
            'ca_ec' => '-2', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '10', 'ec' => '21', 
            'ea' => '18', 
            '_or' => '13', 
            'ca_ec' => '-11', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '9', 'ec' => '16', 
            'ea' => '20', 
            '_or' => '17', 
            'ca_ec' => '-7', 
            'ea_or' => '3',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '12', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '8', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '12', 
            'ea' => '24', 
            '_or' => '11', 
            'ca_ec' => '6',	 
            'ea_or' => '13',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '15', 
            'ea' => '21', 
            '_or' => '12', 
            'ca_ec' => '-1', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '14', 
            'ea' => '22', 
            '_or' => '12', 
            'ca_ec' => '1',	 
            'ea_or' => '10',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '14', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '13', 
            'ea' => '20', 
            '_or' => '13', 
            'ca_ec' => '1', 
            'ea_or' => '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '15', 
            'ea' => '16', 
            '_or' => '13', 
            'ca_ec' => '3', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '16', 
            'ea' => '9', 
            '_or' => '20', 
            'ca_ec' => '1', 
            'ea_or' => '-11',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '12', 
            'ea' => '20', 
            '_or' => '11', 
            'ca_ec' => '5', 
            'ea_or' => '9',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '2', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '17', 
            'ea' => '14', 
            '_or' => '13', 
            'ca_ec' => '0', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '16', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '1', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '-2', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '24', 'ec' => '9', 
            'ea' => '12', 
            '_or' => '16', 
            'ca_ec' => '15',	 
            'ea_or' => '-4',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '-1', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '18', 
            'ca_ec' => '2',	 
            'ea_or' => '-3',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '21', 'ec' => '14', 
            'ea' => '18', 
            '_or' => '11', 
            'ca_ec' => '7', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '14', 
            'ea' => '22', 
            '_or' => '15', 
            'ca_ec' => '1', 
            'ea_or' => '7',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '14', 
            'ea' => '14', 
            '_or' => '15', 
            'ca_ec' => '5',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '15', 
            'ea' => '15', 
            '_or' => '12', 
            'ca_ec' => '5', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '14', 
            'ea' => '18', 
            '_or' => '13', 
            'ca_ec' => '3', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '13', 
            'ea' => '20', 
            '_or' => '18', 
            'ca_ec' => '1', 
            'ea_or' => '2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '10', 
            'ea' => '18', 
            '_or' => '15', 
            'ca_ec' => '6', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '16', 
            'ea' => '22', 
            '_or' => '12', 
            'ca_ec' => '0',	 
            'ea_or' => '10',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '11', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '17', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '-2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '12', 
            'ca_ec' => '5', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '16', 
            'ea' => '14', 
            '_or' => '19', 
            'ca_ec' => '0',	 
            'ea_or' => '-5',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '18', 
            'ea' => '16', 
            '_or' => '16', 
            'ca_ec' => '-7', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '13', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '-1', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '14', 
            'ea' => '16', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '16', 
            'ea' => '16', 
            '_or' => '11', 
            'ca_ec' => '0', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '2', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '17', 
            'ca_ec' => '0', 
            'ea_or' => '2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '16', 
            'ea' => '16', 
            '_or' => '18', 
            'ca_ec' => '1',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '17', 
            'ea' => '13', 
            '_or' => '16', 
            'ca_ec' => '0',	 
            'ea_or' => '-3',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '7', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '12', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '12', 
            'ea' => '20', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '4', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '13', 
            'ea' => '22', 
            '_or' => '12', 
            'ca_ec' => '-1',	 
            'ea_or' => '10',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '14', 
            'ea' => '12', 
            '_or' => '21', 
            'ca_ec' => '1',	 
            'ea_or' => '-9',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '11', 
            'ea' => '16', 
            '_or' => '19', 
            'ca_ec' => '7',	 
            'ea_or' => '-3',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '13', 
            'ea' => '21', 
            '_or' => '12', 
            'ca_ec' => '1', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '12', 
            'ea' => '19', 
            '_or' => '12', 
            'ca_ec' => '5', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '11', 
            'ea' => '18', 
            '_or' => '16', 
            'ca_ec' => '9', 
            'ea_or' => '2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '9', 
            'ea' => '21', 
            '_or' => '15', 
            'ca_ec' => '9', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '-2', 
            'ea_or' => '6',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '13', 
            'ca_ec' => '3', 
            'ea_or' => '6',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '19', 'ec' => '12', 
            'ea' => '16', 
            '_or' => '17', 
            'ca_ec' => '7',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '14', 
            'ea' => '18', 
            '_or' => '17', 
            'ca_ec' => '-1', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '-1', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '17', 
            'ea' => '15', 
            '_or' => '15', 
            'ca_ec' => '0', 
            'ea_or' => '0',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '20', 'ec' => '13', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '7', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '16', 
            'ea' => '16', 
            '_or' => '18', 
            'ca_ec' => '-3',	 
            'ea_or' => '-2',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '10', 
            'ea' => '21', 
            '_or' => '16', 
            'ca_ec' => '7', 
            'ea_or' => '5',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '21', 'ec' => '11', 
            'ea' => '16', 
            '_or' => '14', 
            'ca_ec' => '10', 
            'ea_or' => '2',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '24', 'ec' => '12', 
            'ea' => '17', 
            '_or' => '18', 
            'ca_ec' => '12',	 
            'ea_or' => '-1',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '18', 
            'ea' => '21', 
            '_or' => '12', 
            'ca_ec' => '-1', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '13', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '0', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '14', 'ec' => '16', 
            'ea' => '16', 
            '_or' => '19', 
            'ca_ec' => '-2',	 
            'ea_or' => '-3',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '15', 
            'ea' => '22', 
            '_or' => '14', 
            'ca_ec' => '0', 
            'ea_or' => '8',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '15', 
            'ea' => '19', 
            '_or' => '14', 
            'ca_ec' => '-3', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '15', 'ec' => '8', 
            'ea' => '19', 
            '_or' => '16', 
            'ca_ec' => '7', 
            'ea_or' => '3',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '12', 
            'ea' => '15', 
            '_or' => '22', 
            'ca_ec' => '6',	 
            'ea_or' => '-7',
            'style' => 'ASIMILADOR'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '17', 
            '_or' => '16', 
            'ca_ec' => '2', 
            'ea_or' => '1',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '22', 'ec' => '10', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '12', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '10', 
            'ca_ec' => '4', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '12', 
            'ea' => '20', 
            '_or' => '12', 
            'ca_ec' => '1', 
            'ea_or' => '8',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '19', 
            'ea' => '11', 
            '_or' => '16', 
            'ca_ec' => '-8',	 
            'ea_or' => '-5',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '22', 'ec' => '10', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '12', 
            'ea_or' => '4',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '13', 'ec' => '12', 
            'ea' => '20', 
            '_or' => '12', 
            'ca_ec' => '1', 
            'ea_or' => '8',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '14', 
            'ea' => '20', 
            '_or' => '15', 
            'ca_ec' => '2', 
            'ea_or' => '5',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '16', 'ec' => '16', 
            'ea' => '22', 
            '_or' => '13', 
            'ca_ec' => '0', 
            'ea_or' => '9',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '12', 'ec' => '12', 
            'ea' => '22', 
            '_or' => '28', 
            'ca_ec' => '0',	 
            'ea_or' => '-6',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '15', 
            'ea' => '18', 
            '_or' => '14', 
            'ca_ec' => '2', 
            'ea_or' => '4',
            'style' => 'ACOMODADOR'],

            ['campus' => 'Turrialba',
            'ca' => '11', 'ec' => '19', 
            'ea' => '11', 
            '_or' => '16', 
            'ca_ec' => '-8',	 
            'ea_or' => '-5',
            'style' => 'DIVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '18', 'ec' => '14', 
            'ea' => '17', 
            '_or' => '10', 
            'ca_ec' => '4', 
            'ea_or' => '7',
            'style' => 'CONVERGENTE'],

            ['campus' => 'Turrialba',
            'ca' => '17', 'ec' => '10', 
            'ea' => '20', 
            '_or' => '19', 
            'ca_ec' => '7', 
            'ea_or' => '1',
            'style' => 'ASIMILADOR']
        ]);
    }
}
