<?php

use Illuminate\Database\Seeder;

class ProfessorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('professor_type')->insert([
            ['age' => '3', 
             'gender' => 'F', 
             'self_eval' => 'I',
             'teacher_period' => '1', 
             'expertise_area' => 'ND',
             'computer_skill' => 'A',
             'web_based_tech_experience' =>	'N', 
             'website_experience' => 'S', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'NA', 
             'self_eval' => 'I',
             'teacher_period' => '2', 
             'expertise_area' => 'DM',
             'computer_skill' => 'H',
             'web_based_tech_experience' =>	'S', 
             'website_experience' => 'S', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'M', 
             'self_eval' => 'B',
             'teacher_period' => '2', 
             'expertise_area' => 'ND',
             'computer_skill' => 'L',
             'web_based_tech_experience' =>	'N', 
             'website_experience' => 'S', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'M', 
             'self_eval' => 'I',
             'teacher_period' => '1', 
             'expertise_area' => 'DM',
             'computer_skill' => 'A',
             'web_based_tech_experience' =>	'S', 
             'website_experience' => 'N', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'F', 
             'self_eval' => 'B',
             'teacher_period' => '2', 
             'expertise_area' => 'DM',
             'computer_skill' => 'A',
             'web_based_tech_experience' =>	'S', 
             'website_experience' => 'O', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'NA', 
             'self_eval' => 'I',
             'teacher_period' => '3', 
             'expertise_area' => 'DM',
             'computer_skill' => 'L',
             'web_based_tech_experience' =>	'O', 
             'website_experience' => 'N', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'M', 
             'self_eval' => 'B',
             'teacher_period' => '1', 
             'expertise_area' => 'DM',
             'computer_skill' => 'A',
             'web_based_tech_experience' =>	'O', 
             'website_experience' => 'N', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'F', 
             'self_eval' => 'B',
             'teacher_period' => '3', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'L',	
             'web_based_tech_experience' => 'O',	 
             'website_experience' => 'O', 
             'class' => 'Beginner'],

            ['age' => '3', 
             'gender' => 'F', 
             'self_eval' => 'I',
             'teacher_period' => '1', 
             'expertise_area' => 'ND',
             'computer_skill' => 'H',
             'web_based_tech_experience' =>	'O', 
             'website_experience' => 'S', 
             'class' => 'Beginner'],

            ['age' => '1', 
             'gender' => 'M', 
             'self_eval' => 'I',
             'teacher_period' => '3', 
             'expertise_area' => 'ND',
             'computer_skill' => 'H',
             'web_based_tech_experience' =>	'S', 
             'website_experience' => 'S', 
             'class' => 'Intermediate'],

            ['age' => '1', 
             'gender' => 'NA', 
             'self_eval' => 'I',
             'teacher_period' => '1', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'H',	
             'web_based_tech_experience' => 'N',	 
             'website_experience' => 'O', 
             'class' => 'Intermediate'],

            ['age' => '1', 
             'gender' => 'NA', 
             'self_eval' => 'B',
             'teacher_period' => '2', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'A',	
             'web_based_tech_experience' => 'O',	 
             'website_experience' => 'N', 
             'class' => 'Intermediate'],

            ['age' => '1', 
             'gender' => 'M', 
             'self_eval' => 'B',
             'teacher_period' => '3', 
             'expertise_area' => 'ND',
             'computer_skill' => 'A',
             'web_based_tech_experience' =>	'O', 
             'website_experience' => 'O', 
             'class' => 'Intermediate'],

            ['age' => '1', 
             'gender' => 'NA', 
             'self_eval' => 'B',
             'teacher_period' => '3', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'H',	
             'web_based_tech_experience' => 'O',	 
             'website_experience' => 'S', 
             'class' => 'Intermediate'],

            ['age' => '1', 
             'gender' => 'N', 
             'self_eval' => 'A',
             'teacher_period' => '1', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'A',	
             'web_based_tech_experience' => 'S',	 
             'website_experience' => 'O', 
             'class' => 'Intermediate'],

            ['age' => '2', 
             'gender' => 'F', 
             'self_eval' => 'I',
             'teacher_period' => '3', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'H',	
             'web_based_tech_experience' => 'S',	 
             'website_experience' => 'O', 
             'class' => 'Advanced'],

            ['age' => '2', 
             'gender' => 'NA', 
             'self_eval' => 'I',
             'teacher_period' => '2', 
             'expertise_area' => 'ND',
             'computer_skill' => 'L',
             'web_based_tech_experience' =>	'N', 
             'website_experience' => 'S', 
             'class' => 'Advanced'],

            ['age' => '2', 
             'gender' => 'F', 
             'self_eval' => 'A',
             'teacher_period' => '3', 
             'expertise_area' => 'DM',
             'computer_skill' => 'L',
             'web_based_tech_experience' =>	'O', 
             'website_experience' => 'N', 
             'class' => 'Advanced'],

            ['age' => '2', 
             'gender' => 'F', 
             'self_eval' => 'A',
             'teacher_period' => '1', 
             'expertise_area' => 'OT',	
             'computer_skill' => 'H',	
             'web_based_tech_experience' => 'S',	 
             'website_experience' => 'S', 
             'class' => 'Advanced'],

            ['age' => '2', 
             'gender' => 'M', 
             'self_eval' => 'I',
             'teacher_period' => '2', 
             'expertise_area' => 'ND',
             'computer_skill' => 'H',
             'web_based_tech_experience' =>	'S', 
             'website_experience' => 'S', 
             'class' => 'Advanced']
        ]);
    }
}
